name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Questo è il branch principale di sviluppo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nuxt build --preset github_pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git clone --branch gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cd gh-pages

          rm -rf *
          cp -r ../.output/public/* .

          git add .
          git commit -m 'Deploy to GitHub Pages'
          git push origin gh-pages
